/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/action-button/index.vue')['default']
    Active: typeof import('./src/components/UI/field/src/active.vue')['default']
    Breadcrumb: typeof import('./src/components/UI/breadcrumb.vue')['default']
    Descriptions: typeof import('./src/components/UI/descriptions/src/descriptions.vue')['default']
    Field: typeof import('./src/components/UI/field/src/field.vue')['default']
    Filebox: typeof import('./src/components/UI/fileView/filebox.vue')['default']
    FilePreview: typeof import('./src/components/UI/fileView/filePreview.vue')['default']
    FileView: typeof import('./src/components/UI/fileView/src/fileView.vue')['default']
    Form: typeof import('./src/components/UI/form/src/form.vue')['default']
    Grid: typeof import('./src/components/UI/grid/src/grid.vue')['default']
    'Grid.item': typeof import('./src/components/UI/grid/src/grid.item.vue')['default']
    'Group.btn': typeof import('./src/components/UI/group-btn/src/group.btn.vue')['default']
    Header: typeof import('./src/components/UI/header/src/header.vue')['default']
    Menu: typeof import('./src/components/UI/menu/src/menu.vue')['default']
    Pagination: typeof import('./src/components/UI/pagination/src/pagination.vue')['default']
    RichText: typeof import('./src/components/UI/richText/index.vue')['default']
    RollList: typeof import('./src/components/roll-list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search-input/index.vue')['default']
    'Simple.page': typeof import('./src/components/UI/table/components/Simple.page.vue')['default']
    SimpleDialog: typeof import('./src/components/simple-components/simple-dialog/index.vue')['default']
    SimpleDialogDiv: typeof import('./src/components/simple-components/simple-dialog/simple-dialog-div.vue')['default']
    SimpleDrawer: typeof import('./src/components/simple-components/simple-drawer/index.vue')['default']
    SimpleFormItem: typeof import('./src/components/simple-components/simple-form-item/index.vue')['default']
    StepLine: typeof import('./src/components/UI/step/src/stepLine.vue')['default']
    'Sub.menu': typeof import('./src/components/UI/menu/src/sub.menu.vue')['default']
    Table: typeof import('./src/components/UI/table/index.vue')['default']
    'Table.column': typeof import('./src/components/UI/table/components/Table.column.vue')['default']
    Upload: typeof import('./src/components/UI/upload/index.vue')['default']
  }
}
